version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"
  jobs:
    pre_build:
      - voici build --contents notebooks --apps lab --apps retro

conda:
  environment: build-environment.yml

sphinx:
   configuration: docs/conf.py
