version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"
  jobs:
    post_build:
      - voici build --contents content --apps lab --apps retro --output-dir _readthedocs/html/_static/lite

conda:
  environment: build-environment.yml

sphinx:
   configuration: conf.py
