name: build-env
channels:
  - conda-forge
dependencies:
  - myst-parser
  - pip
  - pydata-sphinx-theme
  - python
  - jupyter_server
  - jupyterlite-core >=0.1.0,<0.2.0
  - pip:
    - jupyterlite-xeus-python >=0.8.0,<0.9.0
    - voici >=0.3.3,<0.4.0
